// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApiLinq.Models
{
    public partial class Rol
    {
        public Rol()
        {
            Usuario = new HashSet<Usuario>();
        }

        public int Idrol { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool? Condicion { get; set; }

        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}